### ISSUE TITLE
Google map doesn't show map controller And drag moving on map not working properly?

### ISSUE THREAD

**Issue by hengseyha** [inocan-group/vue3-google-map#103]
Please help, google map doesn't show map control

**Comment by HusamIbrahim** [comment]
Can you please share a reproduction? You can use https://vite.new/vue

**Comment by hengseyha** [comment]
Hi @HusamIbrahim ,

Please check the link here:
https://camrealtyfrontend.web.app/

And drag on map also not working properly. Can you check this also?

**Comment by HusamIbrahim** [comment]
TypeScript shouldn't be a problem. Can you share a minimal reproduction on StackBlitz or CodeSandbox (or even a repo)? Without that I can't help much I'm afraid.

**Comment by hengseyha** [comment]
> 

Let me prepare this.

**Comment by HoekWax** [comment]
@hengseyha did you find a way to make the drag work properly ?
When I disable draggable on the map, the cursor is the default one which is good
When I enable it, it's the grab cursor but it doesn't work

**Comment by YassineChe** [comment]
Same here!

**Comment by olgber** [comment]
Same here, the draggable cursor is there, but I can not drag the map.

**Comment by olgber** [comment]
If I remove the draggable option from the Marker component, the map gets draggable.

**Comment by HusamIbrahim** [comment]
@olgber Do you mean dragging the map or a marker. Can you share an example?

**Comment by olgber** [comment]
I mean dragging on the map is not working when the marker is draggable. 
If I set the marker option draggable to false, then the map becomes draggable.

<GoogleMap
    ref="mapRef"
    :api-promise="apiPromise"
    style="width: 100%; height: 300px"
    :center="center"
    :map-type-control="true"
    :fullscreen-control="true"
    :zoom="15">
    <Marker
      ref="mapMarkerRef"
      :options="markerOptions"
      @dragend="test($event)" />
  </GoogleMap>

**Comment by HusamIbrahim** [comment]
Seems to work fine on latest

https://github.com/inocan-group/vue3-google-map/assets/39692071/659a3a31-69ea-4b28-a2b8-c50236ee7676

**Comment by olgber** [comment]
I am using "vue3-google-map": "^0.19.0"

**Comment by olgber** [comment]
It was the anchorPoint option that prevented the dragging, removed it and it is working fine now. 
Thanks for your assistance :)
