### ISSUE TITLE
SameSite cookie complaint from chrome browser when using google's icons for markers

### ISSUE THREAD

**Issue by RustyJoeM** [inocan-group/vue3-google-map#109]
Hello,

when using the vue3-google-map plugin inside my SPA frontend app, i keep getting errors/warnings in developer console:

> Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute

e.g. for:
```html
<Marker
    ...
    :options="{ icon: 'http://maps.google.com/mapfiles/kml/paddle/wht-circle.png')}"
/>
...etc...
```

being frontend beginner, I am not sure if i understand the core of issue properly, but i believe that:
 - this plugin should allow/be able to change the cookies/headers settings for it's internal requests for icons being requested from "different" domain?

More error details dumped in the chrome's console:

```
Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.

Resolve this issue by updating the attributes of the cookie:

- Specify `SameSite=None` and `Secure` if the cookie should be sent in cross-site requests. This enables third-party use.
- Specify `SameSite=Strict` or `SameSite=Lax` if the cookie should not be sent in cross-site requests

Affected resources:

4 cookies

Name | Domain & Path
-- | --
HSID | .google.com/
APISID | .google.com/
SID | .google.com/
SIDCC | .google.com/

4 requests

wht-circle.png
blu-circle.png
wht-circle.png
blu-circle.png
```

**Comment by HusamIbrahim** [comment]
I believe we don't have control over this we're just a simple wrapper around the Google Maps Javascript API
