### ISSUE TITLE
Use of HeatmapLayer

### ISSUE THREAD

**Issue by pvalette** [inocan-group/vue3-google-map#120]
Hello,

First thank for this package.

I saw that you have the HeatmapLayer but there is no documentation or sample

I tried to implement a heatmap with options { radius:20, data[ {lat:..., lng:...], ...} but the layer never appeared

If you have a sample, or doc, really appreciate, thank

**Comment by JoseGoncalves** [comment]
Hi @pvalette, please check https://github.com/JoseGoncalves/vue-google-maps/tree/heatmap/

**Comment by HusamIbrahim** [comment]
Refer to my comment here for a basic example https://github.com/inocan-group/vue3-google-map/issues/76#issuecomment-1226371053

**Comment by HusamIbrahim** [comment]
Added to readme
