### ISSUE TITLE
open and close  infowindow

### ISSUE THREAD

**Issue by mansour161** [inocan-group/vue3-google-map#128]
hi
i have two problem . 
1- when i have a MarkerCluster and want to select second marker , Infowindow of first marker was not closed automatic
2 - when i want to click into map , Infowindow is not closed

thanks

**Comment by mansour161** [comment]
hi

**Comment by theyokohamalife** [comment]
@HusamIbrahim @yankeeinlondon 

Calling the `.close()` method on the instance of infoWindow by the ref on InfoWindow doesn't seem to be working. Short example:

```
<template>
<InfoWindow ref="infoWindowRef" />
</template>

<script>
const infoWindowRef= ref(null)

closeInfoWindow() {
  infoWindowRef.value.infoWindow.close() // has no effect
}
</script>
```

**Comment by theyokohamalife** [comment]
It looks like there is a PR that's been approved but not merged yet that addresses this issue. Any idea on when it will be released?

https://github.com/inocan-group/vue3-google-map/pull/125

**Comment by HusamIbrahim** [comment]
> @HusamIbrahim @yankeeinlondon
> 
> Calling the `.close()` method on the instance of infoWindow by the ref on InfoWindow doesn't seem to be working. Short example:
> 
> ```
> <template>
> <InfoWindow ref="infoWindowRef" />
> </template>
> 
> <script>
> const infoWindowRef= ref(null)
> 
> closeInfoWindow() {
>   infoWindowRef.value.infoWindow.close() // has no effect
> }
> </script>
> ```

This should work on the lates version `v0.16.0`. OP's original request for automatically closing info windows isn't supported atm.
