### ISSUE TITLE
Accessing customMarker from CustomMarker Component is undefined

### ISSUE THREAD

**Issue by manuelarling** [inocan-group/vue3-google-map#130]
Im trying to get the customMarker (google.maps.CustomMarker) Object from the CustomMarker component via ref:

`<CustomMarker ref="marker" :options="marker.options">
...
</CustomMarker>`

but when im trying this:

`const marker = ref()

const customMarker = marker.value.customMarker`

customMarker ist undefined, but the ref is fine.

It is also working with the normal Marker Component.

**Comment by HusamIbrahim** [comment]
Can you please provide a minimal reproduction? You can use https://vite.new/vue

**Comment by manuelarling** [comment]
Sorry for the late answer. Here is a simple example:
https://stackblitz.com/edit/vitejs-vite-elvdes?file=src%2FApp.vue
You can see in the console, that the markerRef has a marker property but the customMarker ref has a undefined customMarker property.

**Comment by manuelarling** [comment]
Accidentally closed even though the issue still persists. I apologize.
