### ISSUE TITLE
Docs website is down

### ISSUE THREAD

**Issue by BenJackGill** [inocan-group/vue3-google-map#139]
There are links pointing to https://vue3-google-map.netlify.app/ as the documentation and example website, but that website is down.

**Comment by Krislunde** [comment]
Is this repo abandoned?

**Comment by mobreviews** [comment]
looks like the website changed but the link hasn't been updated.  `https://vue-map.netlify.app/`

**Comment by BenJackGill** [comment]
@Krislunde there was an update 2 months ago, so I think it is still maintained.

**Comment by HusamIbrahim** [comment]
Docs site is now up at https://vue3-google-map.com/
