### ISSUE TITLE
vue3-google-map:16 Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by dinukadesilva** [inocan-group/vue3-google-map#144]
We are trying to use the vue3-google-map module inside out vue project. And we continuously get this error on the browser console. Do you have any advice?

https://github.com/access-ci-org/step-2023-shared-webapps-library

<img width="523" alt="Screenshot 2023-06-22 at 10 52 28" src="https://github.com/inocan-group/vue3-google-map/assets/10680296/58be2529-d67d-4a0a-a851-9bae61c254fe">

**Comment by wu-psvneo** [comment]
I can confirm this error (using the CDN version and script-tag).

**Comment by MadeInShineA** [comment]
I also have this error

**Comment by 51303014** [comment]
I am also facing same this issue

**Comment by HusamIbrahim** [comment]
This should be fixed in the latest version `v0.16.0`. Example pen:
[https://codepen.io/husamibrahim/pen/poQXZbR](https://codepen.io/husamibrahim/pen/poQXZbR)
