### ISSUE TITLE
Error when using MarkerCluster with CustomMarker

### ISSUE THREAD

**Issue by LucasDemea** [inocan-group/vue3-google-map#146]
Hi,
I get this error:

```console 
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'fromLatLngToDivPixel')
```
<details>
<summary>
trace
</summary>

    at _.bk.draw (index.js:26:1)
    at _.bk.setOptions (index.js:27:1)
    at J.immediate (index.js:40:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:1)
    at job (runtime-core.esm-bundler.js:1756:1)
    at flushPreFlushCbs (runtime-core.esm-bundler.js:304:1)
    at updateComponentPreRender (runtime-core.esm-bundler.js:5832:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5750:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:1)

</details>

This happens only when I'm grouping `CustomMarker` in a `MarkerCluster`

```vue
<GoogleMap
    ref="mapRef"
    :api-key="gmapKey"
    style="width: 100%; height: 100%"
    :styles="gmapsTheme"
    :map-type-control="false"
    :zoom="6"
    :disable-default-ui="true"
  >
    <MarkerCluster
      v-if="Object.keys(markers).length"
    >

      <CustomMarker
        v-for="(marker, i) in markers"
        :key="i"
        :options="{
          position: marker,
          anchorPoint: 'BOTTOM_CENTER',
        }"
      >
        // Custom marker code, nothing special here
      </CustomMarker>
    </MarkerCluster>
  </GoogleMap>
```

EDIT: the error happens when updating the `markers` list (thus causin a rerender).

EDIT2: seems related to https://stackoverflow.com/a/6657723

**Comment by HusamIbrahim** [comment]
Can you provide a minmial reproduction so I can take a look? You can use [vite.new/vue](https://vite.new/vue)

**Comment by LucasDemea** [comment]
I can't reproduce the issue in a minimal repro, but I managed to solve my issue : I needed to update the `MarkerCluster` by changing its key, when updating the `CustomMarker` list.
Somehow the `ClusterMarker` is not refreshing itself when updating its child `CustomMarker`s.

**Comment by hector170793** [comment]
I'm having the same issue. @LucasDemea can you show me how did you solve it, please? When a change my view from an empty map to the view with the MarkerCluster I got the same error

**Comment by ArtemGrachov** [comment]
Conditions to reproduce:

- trigger markers array change
- use array item index as v-for item's key

```
        v-for="(marker, i) in markers"
        :key="i"
```

I got same issue and solved it adding id to markers array.

```
        v-for="marker in markers"
        :key="marker.id"
```

In my case, markers array was generated from list of shops taken from the server, so each one had their own unique id field.
