### ISSUE TITLE
minimal node.js engine 

### ISSUE THREAD

**Issue by JoseGoncalves** [inocan-group/vue3-google-map#156]
Recently (in 0.16.0 release) the node.js requirement was set at `>=18.17.0` in `package.json`.
Is there any specific reason to set such an higher minimal node.js version?
I'm asking this because in some of my deployments I use Debian's pakaging of node.js, and in bookworm the version that is packaged is 18.13.0 (https://packages.debian.org/bookworm/nodejs).

**Comment by HusamIbrahim** [comment]
Hey @JoseGoncalves 

This was changed as part of an overhaul to our build system but it doesn't necessarily need to be that high. We can certainly relax the requirement if it's causing you issues.

**Comment by JoseGoncalves** [comment]
Hi @HusamIbrahim 

AFAIK, the only really "issue" is to receive the following warning when performing a `npm i`:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'vue3-google-map@0.17.0',
npm WARN EBADENGINE   required: { node: '>=18.17.0' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '9.2.0' }
npm WARN EBADENGINE }
```

Maybe setting to `>=18.13.0` would be better to avoid the warning to users that use the `nodejs` package from Debian 12 (bookworm) or Ubuntu 23.04 (lunar).

**Comment by HusamIbrahim** [comment]
Honestly I think we can set it as low as `>=16.11.0` to match Vue's if we can. Our other dependencies don't specify a requirement for node versions so if we can go as deep as Vue's that'd be great.
