### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by andcl** [inocan-group/vue3-google-map#160]
[vue3-google-map.netlify.app](https://vue3-google-map.netlify.app/)
Sorry to inform you from here, but documentation site is down from yesterday.
Thanks.

**Comment by bchewy** [comment]
bump it's still down

**Comment by JoelYoung01** [comment]
Still noticed it's down.

**Comment by MaksSieve** [comment]
and it's still down...

**Comment by HusamIbrahim** [comment]
We are in the process of updating our documentation site and moving to a different hosting provider. In the meantime you can refer to the readme. It has everything except for the rendered examples.

**Comment by HusamIbrahim** [comment]
Docs site is now up at https://vue3-google-map.com/
