### ISSUE TITLE
Changing markers cause flickering

### ISSUE THREAD

**Issue by gerritvanaaken** [inocan-group/vue3-google-map#17]
Maybe this is more like a howto than a bug. If I change the data basis for the markers (the 'stations' Array), all markers shortly disappear before they appear again. This happens even when there is no actual change for the active markers.

At the corresponding list view (with the exact same data basis), Vue does the mutation/merging smoothly (even animated). But on the map, the markers get deleted and re-created (so it seems.) Here ist some code from the Component:

`````
<GoogleMap
  id="map"
  ref="mapRef"
  :api-key="apikey"
  style="width: 100%; height: 60vh; max-height: 120vw"
  :center="center"
  :zoom="zoom"
>
  <Marker
    v-for="station in stations"
    :key="station.id"
    :options="{
      title: station.name,
      position: { lat: station.geoPos.lat, lng: station.geoPos.lng },
      icon: markerIcon(station)
    }"
  />
</GoogleMap>
`````

`````
computed: {
  apikey () {
    return this.$store.state.googlemapsapikey;
  },
  zoom () {
    return this.$store.state.map.zoom;
  },
  center () {
    return this.$store.state.map.center;
  },
  stations () {
    return this.$store.state.stations;
  }
}
`````

And here is some code from the global Vuex store:

`````
state () {
  return {
    googlemapsapikey: 'xxxxxxxxxxx',
    map: {
      radius: 10000,
      zoom: 14,
      center: {
        lat: 49.7971716, 
        lng: 9.9269455
      }
    },
    stations: []
  };
},
mutations: {
  fetchStations (state) {
    Axios.get('/station/geo', {
      params: {
        lat: state.map.center.lat,
        lng: state.map.center.lng,
        radius: state.map.radius || 10000
      } 
    }).then(response => {
      if (response.status === 200) {

        // change the reactive station data
        state.stations = response.data;
      }
    });
  }
`````

Is there a way to enable smart/lazy marker changing behaviour?

**Comment by HusamIbrahim** [comment]
Hey @gerritvanaaken,

You're right we're currently watching the config/options object for each of these components and destroying then recreating them when the watcher fires. It seems that Vue performs a simple comparison for objects and will fire the watcher even if non of the child properties has changed. Please refer to these:
- [https://github.com/vuejs/vue/issues/5776#issuecomment-304570693](https://github.com/vuejs/vue/issues/5776#issuecomment-304570693)
- [https://forum.vuejs.org/t/watch-doesnt-fire-if-value-is-same/38002/2](https://forum.vuejs.org/t/watch-doesnt-fire-if-value-is-same/38002/2)

The only way around this is to perform deep comparison on the config objects to pinpoint the properties that have changed and react to them. It would require special treatment for each property though (and consideration of duration/easing for animations). We're sort of doing this kind of special treatment for the `zoom` and `center` props of the base `GoogleMap` component. Doing it for all properties of other components is another beast though.

**Comment by dudeo4106** [comment]
Than you for providing us this awesome library.
We are a user of this open source and we are in desperate need your help about adding this specific function to the library since it is essential for our system.
We would be appreciated if you could help us about it. Thank you again.

**Comment by ksnyde** [comment]
@dudeo4106 this is a feature request and like all feature requests we're open to a PR if you need this please consider this path

**Comment by gmalignon** [comment]
I need the same thing fixed too. I'm willing to help if you tell me how to get started. It seems to me that if there's a way to compare the options for the existing Marker in the watch section, it would be easy to not update the marker.

**Comment by HusamIbrahim** [comment]
@gmalignon Yes that's something I had considered (the deep object comparison) but didn't implement, fearing perf issues. Might give it a try and see how it goes.

**Comment by gmalignon** [comment]
I ended up managing the markers myself with the map reference. I simply keep track of the one that's clicked and change the icon dynamically, also resetting the one previously selected. I also use setVisible true or false depending on if I want to show the marker or not. There's no flickering at all (since the markers are not removed and added again) and it's very quick.
