### ISSUE TITLE
Unable to nest inforwindow inside the CustomMarker to toggle

### ISSUE THREAD

**Issue by matrixmandeep** [inocan-group/vue3-google-map#175]
1) Unable to nest inforwindow inside the CustomMarker to toggle:
**Below is my code**
` <Marker :options="{ position: marker.position }" :clickable="true" :draggable="true" @click="openMarker(true)"
        @closeclick="openMarker(false)">
        <div style="text-align: center" @click="setInfoWindow(marker, index)">
          <img :src="customMapMarker.url" width="37" height="50" />
        </div>
        <InfoWindow v-model="showInfoWindow" :options="{ position: center }" :opened="showInfoWindow"
          @closeclick="showInfoWindow = false">
          <div v-html="infoWindow.content"></div>
        </InfoWindow>
      </Marker>`
      
      2) also I want the infowindow to stay open on first time I used the v-model but it fails.

**Comment by Eacolt** [comment]
如何解决这个问题 ？

**Comment by HusamIbrahim** [comment]
This is not supported unfortunately

**Comment by Uhliber** [comment]
I am having the same requirement. Is it still unsupported? Is there a workaround to make it work?

**Comment by marcosicp** [comment]
same here, any updates?
