### ISSUE TITLE
 "type": "module" missing from package.json

### ISSUE THREAD

**Issue by kylelamoreaux** [inocan-group/vue3-google-map#177]
Unable to build in Vite.

`build error:
file:///workspaces/ad-landing/docs/.vitepress/.temp/app.js:8
import { GoogleMap, Marker, InfoWindow } from "vue3-google-map";
         ^^^^^^^^^
SyntaxError: Named export 'GoogleMap' not found. The requested module 'vue3-google-map' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue3-google-map';
const { GoogleMap, Marker, InfoWindow } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async build (file:///workspaces/ad-landing/node_modules/vitepress/dist/node/serve-qpgewBA8.js:52991:24)`

**Comment by HusamIbrahim** [comment]
Hey @kylelamoreaux 

Which version are you using and can you provide a minimal reproduction?

**Comment by abdurrahmanseyidoglu** [comment]
> Hey @kylelamoreaux
> 
> Which version are you using and can you provide a minimal reproduction?

I think the error happens when Vite builds for SSR

**Comment by HusamIbrahim** [comment]
This is the same issue as #188 . The workaround for now is to add the following to your `vite.config.js`

```
ssr: {
  noExternal: ['vue3-google-map']
}
```

Closing this issue to keep the discussion in one place. Will hopefully release a fix in the coming days.

**Comment by HusamIbrahim** [comment]
Fixed in `v0.20.0`
