### ISSUE TITLE
Consulting is a feature

### ISSUE THREAD

**Issue by yangxi518** [inocan-group/vue3-google-map#19]
Excuse me，when will infowindow be implemented? Thanks！！

**Comment by HusamIbrahim** [comment]
Unfortunately we've got a few bugs to work through before adding any new features.

**Comment by yangxi518** [comment]
Thank you very mach !!!

**Comment by ksnyde** [comment]
@yangxi518 since we are not actively using this component there's not a ton of urgency right now. I'd suggest you consider a pull request if you need this sooner rather than later.

**Comment by ksnyde** [comment]
Tracked here: [Info Windows](https://github.com/inocan-group/vue3-google-map/issues/38)
