### ISSUE TITLE
Documentation Down

### ISSUE THREAD

**Issue by nlassaux** [inocan-group/vue3-google-map#191]
The documentation, hosted on Netlify, seems to be down: https://vue3-google-map.netlify.app/

**Comment by FalkoJoseph** [comment]
Just noticed this as well.

**Comment by HusamIbrahim** [comment]
We are in the process of updating our documentation site and moving to a different hosting provider. In the meantime you can refer to the readme. It has everything except for the rendered examples.

**Comment by darkvertex** [comment]
> New documentation site is up at https://vue3-google-map.com

You may wanna update your npm website url as it still points to the old dead netlify page:
https://www.npmjs.com/package/vue3-google-map

I would've thought it would take the package.json homepage url but it seems not. 🤔

**Comment by HusamIbrahim** [comment]
@darkvertex it should get picked up when we publish a new release
