### ISSUE TITLE
Theme don't work ?

### ISSUE THREAD

**Issue by stephanedemotte** [inocan-group/vue3-google-map#20]
Hello. i try to use theme but nothing change in the map

I'm using it like this

```
  <GoogleMap
    :theme="'ultraLight"
    :zoom="17"
    api-key="***MYAPIKEY***">
  </GoogleMap>
```

I'm doing something wrong or it's a bug ?

Thank !!

**Comment by stephanedemotte** [comment]
Ok got it 

```
  <GoogleMap
    :styles="'[themeARRAY]"
    :zoom="17"
    api-key="***MYAPIKEY***">
  </GoogleMap>
```

**Comment by serginhosis** [comment]
I can't understand, themes not work to me. Can you help-me @HusamIbrahim ?

**Comment by HusamIbrahim** [comment]
@serginhosis Sorry that part of the documentation needs to be updated as it doesn't reflect the latest API. Please refer to this example as it has been updated to reflect the latest ..
https://github.com/inocan-group/vue3-google-map/blob/develop/docs/examples/ThemesExample.vue
