### ISSUE TITLE
google.maps.Marker in the Maps JavaScript API (Deprecated as of February 2023)

### ISSUE THREAD

**Issue by melt-snow** [inocan-group/vue3-google-map#200]
According to https://developers.google.com/maps/deprecations?hl=en, google.maps.Marker will be discontinued.
Google recommends using google.maps.marker.AdvancedMarkerElement.

any plans to do so?

**Comment by rdy3e24r2d2** [comment]
I have the same question.

**Comment by HusamIbrahim** [comment]
Closing this one as it's a duplicate of #199
