### ISSUE TITLE
Feature: HtmlMarkers

### ISSUE THREAD

**Issue by daniel-de-wit** [inocan-group/vue3-google-map#23]
Using a [CustomOverlay](https://developers.google.com/maps/documentation/javascript/examples/overlay-simple) it's possible to mimic the behaviour of a marker while adding the ability to render html using a slot.

The [eregnier/vue2-gmap-custom-marker](https://github.com/eregnier/vue2-gmap-custom-marker/blob/master/gmap-custom-marker.vue) plugin for [diegoazh/gmap-vue](https://github.com/diegoazh/gmap-vue) has this working ([demo](https://vue2-gmap-custom-marker-demo.utopland.net/)). Unfortunately this is all written in Vue2 and not usable in Vue3.

I've tried porting the plugin myself but my JS skills are very limited.

Is there any chance this wonderful package will support this feature in the future?

**Comment by HusamIbrahim** [comment]
Hello @daniel-de-wit

We're certainly looking to expand our feature set. This library was created to address our immediate needs for using basic mapping features with Vue 3. Our focus right now is on fixing any bugs with the initial feature set before adding any new features though.

**Comment by ribrewguy** [comment]
Any movement on this? Only having simple markers is awfully limiting. It would be massively helpful to add custom markup in the markers themselves.

**Comment by web-programmer-here** [comment]
+1 for this feature

**Comment by HusamIbrahim** [comment]
Yeah I realize this is quite a useful feature to have. Will have a go at it when things cool off a bit at work. PRs welcome in the meantime 🙂

**Comment by web-programmer-here** [comment]
@HusamIbrahim is it possible for now to wrap the marker image in a div? I want to style the image but cant target it to style it

**Comment by HusamIbrahim** [comment]
Appreciate the initiative @web-programmer-here!
And kudos to @eregnier for creating this. Really appreciate your support sir 🙏

**Comment by web-programmer-here** [comment]
@HusamIbrahim any chance this feature can be added to the library itself without additional libraries? thanks

**Comment by HusamIbrahim** [comment]
Probably at some point @web-programmer-here. The native API allows for some decent customization level and only when custom markup is really necessary does this feature become useful. Using your sandbox from the plugin repo as an example:
https://codesandbox.io/s/nice-newton-yjgijf?file=/src/frontend/components/Content.vue

**Comment by web-programmer-here** [comment]
Thanks @HusamIbrahim. I need to wrap the image tag in a div

**Comment by tylerclark** [comment]
+1

**Comment by web-programmer-here** [comment]
@HusamIbrahim any chance you can add this feature too when you have time? thanks

**Comment by HusamIbrahim** [comment]
Added in `v0.12.0`
https://github.com/inocan-group/vue3-google-map#custom-marker

**Comment by web-programmer-here** [comment]
@HusamIbrahim amazing work
