### ISSUE TITLE
When did the styling of the info window change?

### ISSUE THREAD

**Issue by michael-gacit** [inocan-group/vue3-google-map#256]
All of a sudden all of my info windows look very strange.
After checking the website/docs I found this:

![image](https://github.com/inocan-group/vue3-google-map/assets/132587190/53205419-11e4-49ef-8fc0-823ab7fbd2bc)

I have excatly the same problem. The close icon looks very off to me.

Since when and why is that? 
How can i fix it or remove it in general?

**Comment by HusamElbashir** [comment]
This is coming from upstream and seems to be intended to improve accessibility. See:
https://issuetracker.google.com/issues/343347275#comment4
