### ISSUE TITLE
Can i put info windows?

### ISSUE THREAD

**Issue by AARP41298** [inocan-group/vue3-google-map#27]
Just kidding, i already check the componentes/index.ts, and i cant found google.maps.InfoWindow declared anywhere

I really want to contribute to this proyect, but im building my first laravel-vue project, so my skills are just growing
But THANK YOU, for this work, is just amazing

**Comment by HusamIbrahim** [comment]
Thanks for the kind words. Info windows  are definitely at the top of our todo list and have been requested before (see #19 for example). Hopefully we can get to it soon.

**Comment by ksnyde** [comment]
Tracked here: [Info Windows](https://github.com/inocan-group/vue3-google-map/issues/38)
