### ISSUE TITLE
Custom controls getting rendered before map is loaded 

### ISSUE THREAD

**Issue by VitAndrGuid** [inocan-group/vue3-google-map#28]

**Comment by ksnyde** [comment]
@HusamIbrahim why is this an enhancement? Seems like defect if it's reproducible. @VitAndrGuid can you explain the steps you're using to reproduce?

**Comment by VitAndrGuid** [comment]
@ksnyde sure can, just instantiate a map with a controller and you can see it gets rendered outside of the map and them onto it after it loads.

reproduction link: https://codesandbox.io/s/vue3-google-maps-custom-control-render-2g68b
