### ISSUE TITLE
Access to the google.maps.Map object?

### ISSUE THREAD

**Issue by nielslynggaard** [inocan-group/vue3-google-map#283]
This is more a question than an issue really, but I'm re-implementing an older solution as a vue application and the old version used something called "[Overlapping Spiderfier](https://www.npmjs.com/package/overlapping-marker-spiderfier)" to have overlapping markers stand out from each other on click (looks and works great).. 

However, the initialization of the spiderfier needs the map object; 

`const oms = new OverlappingMarkerSpiderfier(map, options);`

The question now is; can I access the map object somehow in my template? by ref or otherwise? 

Thank you in advance!

**Comment by nielslynggaard** [comment]
Nevermind, I found it in the docs; 

` watch(() => mapRef.value?.ready, (ready) => {
    if (!ready) return
    console.log(mapRef.value?.map);
  });`

**Comment by MaksSieve** [comment]
Hi, I have same issue now, but this approach causes typescript error `property 'ready' does not exist on type 'never`. And same for 'map' property.
Any Ideas how to make it work?
