### ISSUE TITLE
Polygons reappearing on zoom

### ISSUE THREAD

**Issue by JamieMcDonnell** [inocan-group/vue3-google-map#29]
Hi there,
I created a simple example using your component to render a map and display 2 polygons. It is extracted from a much larger project, but the bug still happens.

I create the polygons, then hide them using `polygon.setMap(null) - when I zoom the map, they reappear.

please take a look at this stackoverflow ticket for details:
https://stackoverflow.com/questions/66987487/polygons-reappearing-on-map-zoom

Thanks for your help!

Jamie

**Comment by ksnyde** [comment]
@JamieMcDonnell the link you pointed to is broken and in the future we would ask that you indicate the steps required to reproduce here in the issue ... ideally with a link to a repo or executable code sample that can be used.

For now I am closing this and you can reopen a new issue if this is still an issue for you.
