### ISSUE TITLE
How do I use google.maps.Point?

### ISSUE THREAD

**Issue by MachariaK** [inocan-group/vue3-google-map#37]
I want markers with different colors and I am wondering where to get` Point` so that the marker can point to the exact position.

The anchor argument should be of the type `google.maps.Point`.

The SVG generator is as follows:

```
export const svgMarker = (fillColor, anchor) => {
  return {
    path:
      "M10.453 14.016l6.563-6.609-1.406-1.406-5.156 5.203-2.063-2.109-1.406 1.406zM12 2.016q2.906 0 4.945 2.039t2.039 4.945q0 1.453-0.727 3.328t-1.758 3.516-2.039 3.070-1.711 2.273l-0.75 0.797q-0.281-0.328-0.75-0.867t-1.688-2.156-2.133-3.141-1.664-3.445-0.75-3.375q0-2.906 2.039-4.945t4.945-2.039z",
    fillColor: fillColor,
    fillOpacity: 1,
    strokeWeight: 0,
    rotation: 0,
    scale: 1.5,
    anchor: anchor
  };
};
```
Also, is it possible to fit bounds?

**Comment by ksnyde** [comment]
Please read the docs and if that doesn't answer your question you'll then need to look at the code. This is an open source problem @MachariaK not a commercial support team. I'm _very_ open to you submitting a PR if you want to improve the documentation or the code _after_ you've gone through this exercise.

I know it would be nice if someone was there to answer questions like this but you should not expect that in open source. This is a learning opportunity for you should you decide to take it.
