### ISSUE TITLE
Multiple Markers

### ISSUE THREAD

**Issue by jasonandress** [inocan-group/vue3-google-map#4]
Can you have multiple markers on the same map?

**Comment by HusamIbrahim** [comment]
@jasonandress Yes you can. Are you having trouble with that?

**Comment by jasonandress** [comment]
@HusamIbrahim no issues, I figured it out. Just add more <Marker> elements.

Can you add an example of setting up an event for the map being repositioned and another example of a Marker being clicked?

**Comment by HusamIbrahim** [comment]
You're right the docs could make use of more examples. Those will be added in soon.
Please refer to [this comment](https://github.com/inocan-group/vue3-google-map/issues/1#issuecomment-720515083) for an example on map repositioning.
