### ISSUE TITLE
Where to register google maps API events listener?

### ISSUE THREAD

**Issue by prasetyaputraa** [inocan-group/vue3-google-map#43]
Where should I register maps API event listeners? I tried to add a listener to click event in `mounted` hooks but the component's map` property is evaluated to null at this point in a component's lifecycle. Thank you.

**Comment by prasetyaputraa** [comment]
The way I do it, is to assign the reference to the map to a `watch` composition API, adding listener to it after the referenced map is ready.

**Comment by prasetyaputraa** [comment]
> The way I do it, is to assign the reference to the map to a `watch` composition API, adding listener to it after the referenced map is ready.

Reopening the issue because somehow this solution does not always work.

**Comment by yulafezmesi** [comment]
Any update on this?

**Comment by HusamIbrahim** [comment]
Hey @prasetyaputraa sorry about the late response. There's a `ready` ref which you can use. @JoseGoncalves shared an example of how he's using it to register event listeners a while back:
https://github.com/inocan-group/vue3-google-map/issues/1#issuecomment-718229226
If this method doesn't work for you or if you have any feedback on ways to improve the API please let me know.

**Comment by JoseGoncalves** [comment]
Hi @prasetyaputraa, you can also check the following usage demo: [vue-google-maps](https://github.com/JoseGoncalves/vue-google-maps.git)

**Comment by prasetyaputraa** [comment]
@HusamIbrahim @JoseGoncalves Sorry, I wonder why did I miss it while browsing the issues. Thank you so much!
