### ISSUE TITLE
Example of Marker Click events

### ISSUE THREAD

**Issue by jasonandress** [inocan-group/vue3-google-map#5]
I need to know what marker was clicked. I've setup a click event on each marker, and it fires the code. Now I need to know what marker was clicked.

<Marker :options="markerOptions1" @click="markerClicked"/>

    const markerClicked = (event: google.maps.MouseEvent) => {
      console.log(event);
    };

event is always undefined.

**Comment by HusamIbrahim** [comment]
Thanks for bringing that up. We need to expose the underlying event.

**Comment by jasonandress** [comment]
Thanks for confirming. Do you have plans to do that soon? Thanks

**Comment by HusamIbrahim** [comment]
> Thanks for confirming. Do you have plans to do that soon? Thanks

This landed in `v0.4.0`.
