### ISSUE TITLE
Failed to resolve loader: @googlemaps/js-api-loader

### ISSUE THREAD

**Issue by mattiaerli97** [inocan-group/vue3-google-map#52]
When I try to install the package `vue3-google-map` with the version `1.12.9` I receive the following error

`Failed to resolve loader: @googlemaps/js-api-loader`

The problem is that, as I can see from the package json, the dependency `@googlemaps/js-api-loader` is included in `devDependencies`, while I believe should be added to the `dependencies` section.

In fact, by installing `@googlemaps/js-api-loader` version latest (mine was 1.12.9), the problem is solved.
Could you please check the code and update the dependencies?
Thanks a lot

**Comment by HusamIbrahim** [comment]
Hi @mattiaerli97 

Thanks for reporting. This is indeed a regression. It was included as a dependency at first but was moved to the peer dependencies section during a modification to the build script.
