### ISSUE TITLE
Uncaught (in promise)  Object { message: "Map: Expected mapDiv of type HTMLElement but was passed null.",

### ISSUE THREAD

**Issue by web-programmer-here** [inocan-group/vue3-google-map#55]
Hi, I am trying to use this library but I get this error:

```
Uncaught (in promise) 
Object { message: "Map: Expected mapDiv of type HTMLElement but was passed null.",....
```

This is how I used it in my content component

```js
....
// script.js
import { GoogleMap, Marker } from "vue3-google-map";

export default {
	name: "Content",
	props: {
		data: Object,
	},
	components: { GoogleMap, Marker },
	data() {
		return {
                    center: { lat: 40.689247, lng: -74.044502 },
.....
```

```js
//component.vue
....
<GoogleMap
	:api-key="API_KEY"
	style="width: 100%; height: 500px"
	:center="center"
	:zoom="15"
>
<Marker :options="{ position: center }" />
</GoogleMap>
...
```

am I doing this properly?

**Comment by web-programmer-here** [comment]
@HusamIbrahim thanks for the quick reply, I tried to create a sandbox but it did not work, I am new to vue and I broke down my template structure like this

```
components
--App
-----index.js
-----script.js
-----component.js
--Content
-----index.js
-----script.js
-----component.js
---index.js
main.js
```

**Comment by HusamIbrahim** [comment]
@HusamIbrahim Can you try https://vite.new/vue? Otherwise maybe share a link to a repo

**Comment by HusamIbrahim** [comment]
@web-programmer-here Can you try https://vite.new/vue? Otherwise maybe share a link to a repo

**Comment by web-programmer-here** [comment]
very strange, maybe something is up with my webpack setup, do you have an example with webpack 5?

```
...js
resolve: {
		alias: {
			//vue$: "vue/dist/vue.esm.js",
			vue: "@vue/compat",
			"@": path.resolve("./src/frontend/"),
			frontend: path.resolve("./src/frontend/"),
		},
		modules: [
			path.resolve("./node_modules"),
			path.resolve(path.join(__dirname, "src/")),
		],
	},
...

module: {
		rules: [
			{
				test: /\.vue$/,
				loader: "vue-loader",
				options: {
					compilerOptions: {
						compatConfig: {
							MODE: 2,
						},
					},
				},
			},
			{
				test: /\.js$/,
				use: "babel-loader",
				exclude: /node_modules/,
			},

```

I using 
```
"vue-cli-plugin-vue-next": "~0.1.4",
"vue-loader": "^17.0.0",
"webpack": "^5.68.0",
"webpack-cli": "^4.9.2"
```

**Comment by web-programmer-here** [comment]
@HusamIbrahim I added you to a private repo that I created to show the error, thank you for your help

**Comment by web-programmer-here** [comment]
@HusamIbrahim I finally managed to create a sandbox here
https://codesandbox.io/s/sample-test-cs7up

I have been trying to figure out what is the issue with this and no luck, been banging my head all day :(

**Comment by HusamIbrahim** [comment]
Hey @web-programmer-here 
Not sure what the issue there is but probably something to do with your webpack config. I tried the Vue CLI scaffolding (webpack based) and your code appears to work there:
https://codesandbox.io/s/shy-darkness-2bh96

**Comment by web-programmer-here** [comment]
@HusamIbrahim Thanks, I don't have this issue with other libraries, is there something specific about this one that it may not work with webpack? the webpack setup is pretty basic, I even disabled `splitChunks` in configuration but still does not work.

**Comment by JoseGoncalves** [comment]
@web-programmer-here This library does work with webpack setups. I use it with a Vue CLI generated project (using webpack on the background) without any issues. Check the following project, maybe it will help you with your setup:
- https://github.com/JoseGoncalves/vue-google-maps

**Comment by web-programmer-here** [comment]
@JoseGoncalves Thanks, I will take a look now

**Comment by HusamIbrahim** [comment]
@web-programmer-here I'd try inspecting the webpack config of a standard Vue CLI project and see if you have something misconfigured:
https://cli.vuejs.org/guide/webpack.html#inspecting-the-project-s-webpack-config

**Comment by web-programmer-here** [comment]
closing this as I decided to use Vue CLI
