### ISSUE TITLE
Examples of using v-for with <Marker>

### ISSUE THREAD

**Issue by jasonandress** [inocan-group/vue3-google-map#6]
I've tried a few ways to iterate my array to create several markers without success. Have you had to do this?

I'm looking to confirm this would work and an example. I've tried the below ways and get some awful Vue errors, i.e.  Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://n

Option 1:
<template v-for="location in state.locations" :key="location.id" >
  <Marker :options="{ position: { lat: location.lat, lng: location.lng } }" @click="markerClicked"/>
</template>

Option 2:
<Marker  v-for="location in state.locations" :key="location.id" :options="{ position: { lat: location.lat, lng: location.lng } }" @click="markerClicked"/>

**Comment by HusamIbrahim** [comment]
@jasonandress Can you provide a reproduction link on jsfiddle or codesandbox?

**Comment by jasonandress** [comment]
Let's see if this works for you, first time using codesandbox. 

https://codesandbox.io/s/sleepy-wozniak-6w9v2?file=/src/App.vue

It works fine when you pre load the array, but once you update the array it throws the error. Press the Click button.

**Comment by jasonandress** [comment]
I've also added a simple v-for with a div below the map. You can see the array of points is increasing, however the Markers are failing.

**Comment by jasonandress** [comment]
@HusamIbrahim  have you taken a look yet?

**Comment by HusamIbrahim** [comment]
Hey thanks for the reproduction link @jasonandress. Will investigate to see why this is happening. Hopefully it's fixable on our end.

**Comment by ksnyde** [comment]
Thanks @jasonandress, we'll definitely get this working. Just juggling things between us. If you felt you had a handle on how this should be fixed we're also open to PRs.

**Comment by JoseGoncalves** [comment]
Any news/workarounds for this issue?

**Comment by HusamIbrahim** [comment]
Hi @JoseGoncalves. Sorry didn't have the time to work on this but will release a fix in the coming days.

**Comment by HusamIbrahim** [comment]
Fixed in `v0.5.2`

**Comment by JoseGoncalves** [comment]
Thanks! I've confirmed that it's now working on my side.
