### ISSUE TITLE
How to update the center of the map when she is already running ?

### ISSUE THREAD

**Issue by Domi-4102** [inocan-group/vue3-google-map#67]
Hi , i tried to edit the property center after initialization but it didn't work 

It didn't update if you pass the same value but the view of the map is different.

**Comment by HusamIbrahim** [comment]
The watcher won't trigger if the value is the same. You'll have to re-center manually I'm afraid.

**Comment by khaledtag98** [comment]
You can use **panTo** as mentioned in google API to change the center:[https://developers.google.com/maps/documentation/javascript/reference/map#Map.panTo](url)

template :
<GoogleMap
    ref="mapRef"
    api-key="YOUR_GOOGLE_API_KEY"
    style="width: 100%; height: width: 100%"
    :center="center"
    :zoom="11"
  >
  
 in your script:
if (mapRef.value?.ready) {
          mapRef.value.map.panTo({ lat: center.lat, lng: center.lng });
}
