### ISSUE TITLE
How to set `region` and `language`

### ISSUE THREAD

**Issue by maninak** [inocan-group/vue3-google-map#7]
We're migrating to vue3 which means we're also migrating from [`vue2-google-maps`](https://www.npmjs.com/package/vue2-google-maps) to `vue3-google-map` (yay!)

In `vue2-google-maps` I could use a [localized map](https://developers.google.com/maps/documentation/javascript/localization) (critical in our use case)

like so:

![image](https://user-images.githubusercontent.com/7542054/101791912-5f513e80-3b04-11eb-9e7b-b315064bf94a.png)

How would I achieve that with this library? I also had a quick look in the source code and it looks like there's no support for it?

Any chance that we can specify `region` and `language` when initializing google maps?

Thank you so much for publishing this library!

**Comment by ksnyde** [comment]
Hi @maninak , I can see how that would be desirable to have. If I understand from your link to the localized map it would appear that this would just be a matter of proxying the config from the Vue component to the Google API. Correct? If so the level of effort is probably pretty simple. I personally am completely swamped but @HusamIbrahim may have time to look at this. Alternatively, if you felt up to it we'd happily accept a PR.

**Comment by JoseGoncalves** [comment]
Just added 2 PRs to support map localization; https://github.com/inocan-group/connect-google-maps/pull/1 & https://github.com/inocan-group/vue3-google-map/pull/8

**Comment by maninak** [comment]
Thank you @joseGon

**Comment by HusamIbrahim** [comment]
This landed in `v0.5.0`. You can now set the `region` and `languauge` props on the `GoogleMap` component.
