### ISSUE TITLE
Cannot get event from @click in <GoogleMap>

### ISSUE THREAD

**Issue by RaskaTheFurry** [inocan-group/vue3-google-map#70]
Hello,
The event @click does fire on click, but when I try to get the event as attribute, it shows me undefined.
@click="foo(e)" and foo(e) is just a simple console log of the event, but I should get MapMouseEvent as it stands in Google Map api, if I understand. I want to get latLng of position my cursor is at.

Can you please help me ?

**Comment by RaskaTheFurry** [comment]
Im sorry, im dumb, it was an error on my part.

Thanks for your help

**Comment by HusamIbrahim** [comment]
No worries. Glad you got it sorted.
