### ISSUE TITLE
Can you access the Marker class instance from a CustomMarker somehow?

### ISSUE THREAD

**Issue by itsjms** [inocan-group/vue3-google-map#83]
I have a CustomMarker in Vue3. I am trying to access the Marker class upon hovering on a CustomMarker so I can set the zIndex to a higher value. Is this possible?

**Comment by itsjms** [comment]
My solution to this was to create another component that embeds CustomMarker and takes a slot. I can then dynamically apply zIndex option as needed.

**Comment by itsjms** [comment]
```
<template>
  <CustomMarker @mouseover="mouseOver = true" @mouseleave="mouseOver = false" :options="customMarkerOptions">
    <slot></slot>
  </CustomMarker>
</template>

<script>
import { 
  CustomMarker
} from 'vue3-google-map';

export default {
  components: {
    CustomMarker
  },
  props: ['position'],
  data: function() {
    return {
      mouseOver: false
    }
  },
  mounted() {},
  computed: {
    customMarkerOptions() {
      return {
        position: this.position, 
        anchorPoint: 'CENTER',
        zIndex: this.mouseOver ? 2 : 1
      }
    }
  },
  methods: {},
  watch: {}
}
</script>
```

**Comment by HusamIbrahim** [comment]
@itsjms I suspect you can just use a class on the custom marker that sets `z-index` on hover. Something like this:

```
.custom-marker:hover {
  z-index: 999 !important;
}
```

**Comment by serdarcevher** [comment]
> ```
> <template>
>   <CustomMarker @mouseover="mouseOver = true" @mouseleave="mouseOver = false" :options="customMarkerOptions">
>     <slot></slot>
>   </CustomMarker>
> </template>
> 
> <script>
> import { 
>   CustomMarker
> } from 'vue3-google-map';
> 
> export default {
>   components: {
>     CustomMarker
>   },
>   props: ['position'],
>   data: function() {
>     return {
>       mouseOver: false
>     }
>   },
>   computed: {
>     customMarkerOptions() {
>       return {
>         position: this.position, 
>         anchorPoint: 'CENTER',
>         zIndex: this.mouseOver ? 2 : 1
>       }
>     }
>   }
> }
> </script>
> ```

Thank you, this solution saved me. Using the styling doesn't work for me.

**Comment by Ektasahusahu** [comment]
```
<CustomMarker @mouseover="onMouseOver" @mouseleave="onMouseLeave" v-for="(property, id) in properties.filter(row => !lowestPrice(row.units)?.featured)" :key="id"  :options="{ position: property.coords, anchorPoint: 'BOTTOM_LEFT',zIndex: mouseOver ? 2 : 1 }">
<div></div>
</CustomMarker>

<script>
const mouseOver = ref(false);
const onMouseOver = () => {
    console.log("mouse hover",mouseOver)
    mouseOver.value = true; 
};

const onMouseLeave = () => {
    console.log("mouse leave",mouseOver)
        mouseOver.value = false; 
};
</script>

```
Code is still not working I don't know what's wrong in this.
Once I hover over a custom marker it should comes up.
