### ISSUE TITLE
Themes Types imports with incorrect path

### ISSUE THREAD

**Issue by S2AON** [inocan-group/vue3-google-map#93]
I have a vite base project, and when I try to build the app there is an error referring to the import of the themes
that have an incorrect path.

"Cannot find module '../themes/index' or its corresponding type declarations. 
2 import * as themes from "../themes/index";"

![image](https://user-images.githubusercontent.com/26665761/183981208-8bd12301-ad06-4a28-a516-2e5d84005e66.png)

I solved the issue by changing the path to: ../../themes/types/index
But as I'm using a serverless solution to run automated builds on the cloud this doesn't work for me.

**Comment by HusamIbrahim** [comment]
Hi @S2AON 

Would you be able to provide a minimal reproduction? I tried building an arbitrary the vite project with the library included and couldn't reproduce this.

**Comment by markcouvaras** [comment]
FYI - This is still a bug.

**Comment by markcouvaras** [comment]
> Hi @S2AON
> 
> Would you be able to provide a minimal reproduction? I tried building an arbitrary vite project with the library included and couldn't reproduce this.

How are we mean to reproduce this? I am trying to deploy to Vercel and this issues happens when a deploy is initiated via Github. Please let us know how to reproduce and I will do it for you?

**Comment by markcouvaras** [comment]
![image](https://user-images.githubusercontent.com/52830148/233053733-21c93568-d5b5-460e-9dd1-fbec20cdc2a1.png)
