### ISSUE TITLE
Using infowindow inside a custom marker?

### ISSUE THREAD

**Issue by web-programmer-here** [inocan-group/vue3-google-map#94]
I was following this doc 
https://vue3-google-map.netlify.app/components/info-window.html#use-with-marker

but looks like `<InfoWindow>` doesnt work with `<CustomMarker>` ? how can I call the infowindow when using custom marker component?

**Comment by RamoFX** [comment]
Did you solve it? If so, how did you do that?

**Comment by web-programmer-here** [comment]
@RamoFX i used the regular marker
