### ISSUE TITLE
Provide custom loader instance 

### ISSUE THREAD

**Issue by alessandrorubio** [inocan-group/vue3-google-map#99]
I was wondering if instead of providing the API_KEY directly in the googleMap component there is a way to provide my own loader instance that is being used in my custom component.

**Comment by HusamIbrahim** [comment]
You can now pass a promise through the `apiPromise` prop which should resolve to the global `google` object. Example:
https://stackblitz.com/edit/vitejs-vite-mgwr2y?file=src/components/HelloWorld.vue
